server:
  port: 6868
eureka:
  client:
    # 是否将自己注册到Eureka
    register-with-eureka: false
    # 是否从eureka中获取信息
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/