server:
  port: 9002

spring:
  application:
    # 指定注册到eureka server 上的服务名称
    name: provider-movie

eureka:
  client:
    service-url:
      # 指定eureka server 通信地址，注意最后的/不能少
      defaultZone: http://localhost:9000/eureka/
    instance:
      # 是否注册IP 到eureka server
      # 如果不指定或为false，那么就会注册主机名到eureka server
      prefer-ip-address: true

security:
  oauth2:
    client:
      client-id: client_2
      client-secret: 123456
    #      user-authorization-uri: http://localhost:9004/oauth/authorize
    #      authorized-grant-types: password
    #      access-token-uri: http://localhost:9004/oauth/token
    #    resource:
    #      userInfoUri: http://localhost:9004/oauth/check_token
    resource:
      userInfoUri: http://localhost:9004/user/info
#    authorization:
#      check-token-access: http://localhost:9004/oauth/check_token

# 配置失败
logging:
  level:
    com:
      microwu:
        cxd: debug
#    com.microwu.cxd.movie.service.UserFeignConfig: debug

# Feign 通用配置, 配置属性的优先级更高
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

  # 启用熔断器
  hystrix:
    enabled: true

  # 启用压缩功能
  compression:
    request: true
    response: true

# 解决Feign/Ribbon 第一次请求失败
# 由于Ribbon 是懒加载的，在首次请求时，才会开始初始化相关类
# 如果初始化时间长，可能默认为响应超时
# 可以设置Hystrix 超时时间，指标不治本
# 配置饥饿加载
ribbon:
  eager-load:
    enabled: true
    # 多个使用，分割
    clients: provider-user

# hystrix 线程隔离，导致安全问题，线程上下文传递不到子线程中
# hystrix 具体源码不清楚，网上抄的配置
# https://blog.csdn.net/yudar1024/article/details/76070214/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
          #这里将线程策略设置为SEMAPHORE
          strategy: SEMAPHORE