server:
  # 监听端口
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com: debug
#
#spring:
#  jackson:
#    serialization:
#      write-dates-as-timestamps: true
