server:
  port: 9004

spring:
  application:
    name: auth-server

  # mysql数据源
  datasource:
    url: jdbc:mysql://192.168.201.128:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # redis
  redis:
    host: 192.168.201.128
    port: 6379


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
