server:
  # 指定Tomcat 端口
  port: 9001

spring:
  application:
    # 指定注册到eureka server 上的服务名称
    name: provider-user

eureka:
  client:
    service-url:
      # 指定eureka server 通信地址，注意最后的/不能少
      defaultZone: http://localhost:9000/eureka/
  instance:
    # 是否注册IP 到eureka server
    # 如果不指定或为false，那么就会注册主机名到eureka server
    prefer-ip-address: true

security:
  oauth2:
    client:
      client-id: client_2
      client-secret: 123456
#      user-authorization-uri: http://localhost:9004/oauth/authorize
#      authorized-grant-types: password
#      access-token-uri: http://localhost:9004/oauth/token
#    resource:
#      userInfoUri: http://localhost:9004/oauth/check_token
    resource:
      userInfoUri: http://localhost:9004/user/info
    authorization:
      check-token-access: http://localhost:9004/oauth/check_token

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS