server:
  port: 8084
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.netflix: DEBUG

zuul:
  routes:
    user-routes:                   # 该配置方式中，user-route只是给路由一个名称，可以任意起名。
      service-id: provider-user
      path: /user/**              # service-id对应的路径
