spring:
  profiles:
    active: dev

  redis:
    host: 192.168.133.134
    port: 6379
    # lettuce
    lettuce:
      # 连接池
      pool:
        max-active: -1
        max-wait: -1ms
        max-idle: 8
        min-idle: 0