server:
  # 监听端口
  port: 8080
  # web应用上下文路径
  servlet:
    context-path: /
  use-forward-headers: true

spring:

  profiles:
    active: dev

  # redis配置
  redis:
    # 数据库索引（默认为0）
    database: 1
    host: 192.168.133.134
    port: 6379
    password:
    # lettuce
    lettuce:
      # 连接池
      pool:
        max-active: -1
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 3000ms

# 日志配置
logging:
  level:
    com:
      microwu: debug

# 线程池配置
thread-pool:
  core-pool-size: 20
  max-pool-size: 50
  queue-capacity: 20
  keep-alive: 20